cate:
  - TV
  - 가방잡화
  - 결혼
  - 경력개발
  - 고가상품
  - 고화질영상
  - 공기질
  - 국내여행
  - 낚시
  - 남성패션
  - 농구
  - 다이어트
  - 달리기
  - 독서
  - 등산
  - 렌탈
  - 반려동물
  - 보석_명품
  - 보험
  - 사진_카메라
  - 숙박업체
  - 스포츠운동용품
  - 신발
  - 아동패션
  - 어학공부
  - 여성패션
  - 온라인상품권
  - 요가
  - 요리
  - 유아교육
  - 의료_제약
  - 인테리어
  - 자전거
  - 주식투자
  - 중고등교육
  - 지도네비게이션
  - 초등교육
  - 초등학교저학년
  - 축구
  - 출산
  - 투자정보
  - 필라테스
  - 해외여행
  - 향수화장품
  - 헬스
  - 홈케어서비스
  - 단말기파손
  - 안전_방역
  - 영화
  - 멤버십포인트
  - 편의점
  - 복권
  - 이사
  - 음악스트리밍
  - 아이돌
  - 렌트
  - 팟캐스트_라디오
  - VR
  - 성인콘텐츠
  - 과정외교육
  - 프로야구
  - 뮤머
  - 반려동물관심
  - 반려동물보유
  - 국책학생(유학생)
  - 대학생
  - 가정외교육
  - 부모서비스
  - 의료_제약
  - 유기농제품
  - 구매력
  - 은행
  - 의사결정자
  - 카드
  - 저신용자
  - 핀테크
  - 간편결제
  - 세금
  - 가상화폐
  - 전기요금
  - 패스트패션브랜드
  - 명품의류
  - 패스트푸드
  - 배달음식
  - 이사서비스
  - 부동산중개
  - 안전_방범
  - 홈케어서비스
  - 동영상스트리밍
  - 유튜브
  - 저가선호
  - E-BOOK
  - AR콘텐츠
  - 대형마트
  - 구매전탐색
  - 오픈마켓
  - 홈쇼핑
  - 해외직접구매
  - 백화점_면세점
  - 가격비교
  - 주차서비스
  - 대중교통
  - 모빌리티공유서비스
  - 블로그
  - 온라인카페
  - 인스타그램
  - SNS
  - 페이스북
  - 온라인뉴스
  - 날씨
  - 고객센터_서비스센터
  - 모바일상품
  - 홈상품
  - MVNO
  - 삼성모바일
  - 애플모바일
  - 5G
  - 속도측정
  - 캐시백
  - 유흥_도박
  - 공공기관
prompts:
  product: |
    너는 마케팅 기획자야.
    아래 조건을 반영해서 주요 소구 고객을 찾기 위한 카테고리를 추천하는 것이 목표야

    A.상품의 특성은 아래와 같아

    {description}

    B. 해당 회원군에 대한 전반적인 설명을 해줘
    - 어떤 데모그래픽을 갖고 있는지, 주된 심리적 동인은 무엇인지, 어떤 것을 소비하는데 관심이 많은지 알려줘 
    - 이들은 주로 어떤 생각을 하고 있으며, 어떤 가치를 중요하게 생각하고, 궁극적으로 무엇을 원하는지에 대해 알려줘
    - 1.데모, 2.주요 심리적 동인, 3.주요 가치, 4. 주요 관심사의 항목으로 나눠서 작성해줘

    C.이에 어떤 카테고리를 참조하여 고객을 찾아야 하는지, 왜 해당 카테고리를 추천하는지 알려줘
    - 카테고리는 {cate} 안의 카테고리 중에서 추천해줘
    - 제공된 문서만 기반으로 해서 카테고리 5개 추천, 그리고 그 이유를 설명해줘. 항목의 제목은 '주요 카테고리 추천' 으로 해줘.
    - 그리고 나서 제공된 문서와 네 생각을 모두 포함해서 카테고리 5개를 추천, 그리고 이유를 설명해줘. '주요 카테고리 추천'에서 추천한 항목은 또 추천하지 않아도 괜찮아. 항목의 제목은 별도로 만들지 말고, '주요 카테고리 추천'의 하위 항목으로 넣어줘
    - 추천 카테고리는 별도의 하위항목 없이 1~10으로 추가해줘


    모든 답변은 자세히 풀어서 설명해줘
    A-B-C의 순서대로 답변을 작성해줘
    알파벳 타이틀에는 ####를, 숫자 타이틀에는 #####를 붙여줘

  product_simple: |
    너는 마케팅 기획자야.
    아래 조건을 반영해서 주요 소구 고객을 찾기 위한 카테고리를 추천하는 것이 목표야

    조건 : {description}

    A.상품의 특성은 아래와 같아

      - 조건의 내용을 15자 이내로 요약해줘

    B. 해당 회원군에 대한 전반적인 설명을 해줘
      - 어떤 데모그래픽을 갖고 있는지, 주된 심리적 동인은 무엇인지, 어떤 것을 소비하는데 관심이 많은지 알려줘 
      - 이들은 주로 어떤 생각을 하고 있으며, 어떤 가치를 중요하게 생각하고, 궁극적으로 무엇을 원하는지에 대해 알려줘
      - 1.데모, 2.주요 심리적 동인, 3.주요 가치, 4. 주요 관심사의 항목으로 나눠서 작성해줘

    C.이에 어떤 카테고리를 참조하여 고객을 찾아야 하는지, 왜 해당 카테고리를 추천하는지 알려줘
      - 카테고리는 {cate} 안의 카테고리 중에서 추천해줘
      - 제공된 문서만 기반으로 해서 카테고리 10개 추천하고 그 이유도 함께 설명해줘 
      - '이유:' 는 작성하지 말 것.
      - {cate} 안에 없는 카테고리는 절대 포함하지 마

    - 모든 답변은 자세히 풀어서 설명해줘
    - A - B - C  의 순서대로 답변을 작성해줘
    - 각 항목별 제목은 아래처럼 해줘
      - A : 상품 정보 요약
      - B : 고객군 특성
      - C : 카테고리 추천

  profile: |
    너는 인간의 심리와 소비에 대해 연구하는 학자야.
    특정 묘사를 기반으로 그것과 가장 어울리는 카테고리를 추천하는 것이 목표야.

    묘사 : {description}

    A.묘사의 내용은 아래와 같아

      - 묘사의 내용을 15자 이내로 요약해줘

    B. 묘사된 대한 전반적인 설명을 해줘
      - 해당 묘사의 주된 심리적 동인은 무엇인지 설명해줘
      - 어떤 생각에 기반하고 있고, 어떤 가치관에 가까우며, 궁극적으로 무엇을 원하는지에 대해 알려줘
      - 해당 묘사를 간단하게 요약하고, 이 묘사에 부합하는 사람들의 특성에 대해서 설명해줘
      - 항목은 아래와 같이 구성해줘
        - 1. 프로파일 요약
        - 2. 주요 심리적 동인
        - 3. 주요 핵심 가치
        - 4. 주요 관심사
        - 해당 항목의 타이틀은 마크다운 ####을 적용해줘
      
    C.이에 어떤 카테고리를 참조하여 고객을 찾아야 하는지, 왜 해당 카테고리를 추천하는지 알려줘
      - 카테고리는 {cate} 안의 카테고리 중에서 추천해줘
      - 제공된 문서만 기반으로 해서 카테고리 10개 추천하고 그 이유도 함께 설명해줘 
      - {cate} 안에 없는 카테고리는 절대 포함하지 마

    - 모든 답변은 자세히 풀어서 설명해줘
    - A-B-C의 순서대로 답변을 작성해줘
    - 각 항목별 제목은 아래처럼 해줘
      - A : 프로파일 정보 요약
      - B : 고객군 특성
      - C : 카테고리 추천
      - 해당 항목의 타이틀은 마크다운 #####을 적용해줘
      - '이유:'를 넣지 말 것.
    - 내가 프롬프트에 입력한 질문은 출력하지 말 것.
    - A 항목 출력할 때 '요약:' 넣지 말 것.
    - A 항목에는 입력한 프롬프트 출력하지 말 것.
    - A 항목의 본문에 앞에 - 붙이고 글자만 입력할 것. 따옴표 붙이지 말 것.
    - 알파벳 타이틀에는 ####를, 숫자 타이틀에는 #####를 붙여줘
